name: Epic
description: Cross-cutting initiative tracking multiple issues
labels: [epic, migration]
body:
  - type: textarea
    id: scope
    attributes: { label: Scope, description: What this epic covers }
  - type: textarea
    id: deps
    attributes: { label: Dependencies, placeholder: "Blocked by #57, #49, …" }
  - type: textarea
    id: deliverables
    attributes: { label: Deliverables, placeholder: "- <deliverable>" }
